### ISSUE TITLE
有没有可能随机生成公网IP，再测试期可用性！

### ISSUE THREAD

**Issue by LakeVilladom** [AceDarkknight/GoProxyCollector#1]

**Comment by AceDarkknight** [comment]
不是很懂你的意思，可以举一个例子说明一下吗

**Comment by LakeVilladom** [comment]
我是随便想的，别笑，意思就是我不去代理网站爬，我自己按照公网IP的规则自己生成IP，然后测试这个IP是否可用，因为爬代理IP也是问题多多，反爬啦，网页DOM结构改变啦。。。

**Comment by AceDarkknight** [comment]
随机生成命中率太低了，不划算。
计算一下255*255*255*255*端口数量，按照端口数量1000算总数就有4,228,250,625,000，而且端口数还可能更大。一个个得验证花费时间太长而且可用的可能不到万分之一，效率太低了。考虑到有些ip会过期，再生成代价更加大。

**Comment by LakeVilladom** [comment]
哈哈 是
