### ISSUE TITLE
有俩AceDarkkinght，AceDarkknight

### ISSUE THREAD

**Issue by LakeVilladom** [AceDarkknight/GoProxyCollector#3]
怎么有俩AceDarkkinght，AceDarkknight

**Comment by AceDarkknight** [comment]
改了一次名字，没有影响吧

**Comment by LakeVilladom** [comment]
影响是没有，就是会get到俩一样的GoProxyCollector，最好改修改彻底把

**Comment by CBDlkl** [comment]
一样的，有个项目名字很想，一个叫in,一个ni。虽然没影响，但是还是希望最好彻底修改。

**Comment by AceDarkknight** [comment]
已修复，先把两个AceDarkkinght，AceDarkknight路径下的都删除，再重新get一次即可

**Comment by LakeVilladom** [comment]
glide.yaml 里面是不是没修过过来

**Comment by AceDarkknight** [comment]
感谢提醒，已修改
